# docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo

#determine version
version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
#defining one volume
volumes:
  mongodbdata: 